swagger: '2.0'
info:
  description: Public API
  version: V1
  title: APIsec REST API
  termsOfService: Terms of service
  license:
    name: Apisec.ai
host: 192.168.1:8080
basePath: /
tags:
  - name: Apisec.ai
    description: Controller
paths:
 /v1/api/sample/get/{id}:
    get:
      tags:
        - tagGet
      summary: summaryGet
      description: descriptionGet
      operationId: operationIdGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: Path Parameter is required
          required: true
          type: string
       
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
  /v1/api/sample/update/{id}:
    put:
      tags:
        - tagPut
      summary: summaryPut
      description: descriptionPut
      operationId: updatePUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: update
          description: Request body is required
          required: true
          schema:
            $ref: ''
        - name: id
          in: path
          description: Path Parameter is required
          required: true
          type: string
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
  /api/v1/sample/delete/{id}:
    delete:
      tags:
        - tagDelete
      summary: summaryDelete
      description: descriptionDelete
      operationId: operationIdDELETE
      consumes:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: required id in params
          required: true
          type: string
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
  /api/v1/sample/create:
    post:
      tags:
        - Tagcreate
      summary: summaryPost
      description: descriptionPost
      operationId: operationIdPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: request
          description: Must contains body parameter
          required: true
          schema:
            $ref: ''
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
