swagger: '2.0'
info:
  description: Public API
  version: V1
  title: REST API
  termsOfService: Terms of service
  license:
    name: Apisec.ai
host: 192.168.1:8080
basePath: /
tags:
  - name: Apisec.ai
    description: Controller
paths:
  /apisec/sample/get/{id}:
    get:
      tags:
        - get
      summary: getUserById
      description: getUserById
      operationId: userByIdGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: Path Parameter is required
          required: true
          type: string
        - name: pageSize
          in: query
          description: Query parameter is required
          required: false
          type: integer
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
  /apisec/sample/update/{id}:
    put:
      tags:
        - update
      summary: UpdateUserById
      description: UpdateUserById
      operationId: UpdateUserByIdPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: update
          description: Request body is required
          required: true
          schema:
            $ref: ''
        - name: id
          in: path
          description: Path Parameter is required
          required: true
          type: string
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
  /apisec/sample/delete/{id}:
    delete:
      tags:
        - delete
      summary: deleteUserById
      description: deleteUserById
      operationId: deleteByIdDELETE
      consumes:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: required id in params
          required: true
          type: string
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
  /apisec/sample/create:
    post:
      tags:
        - create
      summary: createUser
      description: createUser
      operationId: createUserPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: TransferAccount
          description: Request body is required
          required: true
          schema:
            $ref: ''
      responses:
        '200':
          description: The request is OK.
          schema:
            $ref: ''
        '400':
          description: The server did not understand the request
        '404':
          description: The server can not find the requested page.
        '500':
          description: The request was not completed. The server met an unexpected condition.
